[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "7.1", features = ["alloc"] }
util = { path = "../util" }
num-traits = "0.2.17"
